name = "CoreformIGA"
uuid = "5373bc43-13d9-47f9-bf0b-5d26f95c4516"
authors = ["Michael A. Scott <michael.scott@byu.edu> and contributors"]
version = "0.1.0"

[deps]
DocumenterTools = "35a29f4d-8980-5a13-9543-d66fff28ecb8"
GaussQuadrature = "d54b0c1a-921d-58e0-8e36-89d8069c0969"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
